### PR TITLE
Fix linkage and explicit static luabind libraries.

### PR DESCRIPTION
**Pull request by cbalint13**
Hi Sylvain,

Request with small nits: 
   * **explicit** ```std++fs``` for centos8/rhel8
   *  assure ```STATIC``` local **luabind** just like [lua](https://github.com/sylefeb/Silice/blob/master/src/libs/lua/CMakeLists.txt#L21)

---

For more interest, **silice** is included in a weekly rhel/fedora public HDL repo [here](https://copr.fedorainfracloud.org/coprs/rezso/HDL/).

Thanks a lot for your effort towards Silice !
/Cristian.

### CODE REVIEW

**Comment by sylefeb** [comment]
Hi Cristian,

Thanks for the edits! It's also great to know about the rhel/fedora inclusion.

The Lua static change is looking great, tested without issue so far.

Regarding std++fs things are a bit more difficult. I cannot add it always since some compilers (which include it natively I think) do not recognize the library. I had this test below which clearly was not working on your system:

https://github.com/sylefeb/Silice/blob/31fe0c204d7d7b3f5a5190d4e3944211fc68da6b/CMakeLists.txt#L125-L131

I noticed today that pybind11 has in its cmake a more complete test that is likely more robust:

https://github.com/pybind/pybind11/blob/6493f496e30c80f004772c906370c8f4db94b6ec/tests/CMakeLists.txt#L314-L349

Shall we try something like that? Or perhaps a simpler change to my current test would do?

Thank you!
Sylvain

**Comment by cbalint13** [comment]
Hi Sylvian,


Updated and re-tested the PR.


> The Lua static change is looking great, tested without issue so far.

* I kept it, this is important since ```cmake``` may be invoked with SHARED flags in distro's releng.
 
> Regarding std++fs things are a bit more difficult. I cannot add it always since some compilers (which include it natively I think) 

> I noticed today that pybind11 has in its cmake a more complete test that is likely more robust:
> https://github.com/pybind/pybind11/blob/6493f496e30c80f004772c906370c8f4db94b6ec/tests/CMakeLists.txt#L314-L349

* I think pybind11 way would be the best, thanks a lot looking into this, i wasn't fully aware !


> Shall we try something like that? Or perhaps a simpler change to my current test would do?

* [All builds]( https://copr.fedorainfracloud.org/coprs/rezso/HDL/build/4357915/) went nice on {el8, fc35, fc36, fc37} x {x86_64, ppc64le, aarch64}.
* None required / detected needs for ```stdc++fs``` except ```el8``` where things also went fine:
```
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
{...}
-- Output libraries to /builddir/build/BUILD/silice/lib
-- Linking with: stdc++fs
-- Configuring done
-- Generating done
```

> Thank you! Sylvain

Thank you !
/Cristian.

**Comment by sylefeb** [comment]
Excellent, thanks! Working great here as well. 

I propose to add a bit of licensing info around the test? see [patch.txt](https://github.com/sylefeb/Silice/files/8609473/patch.txt)

(I did not find how to push on the PR :) )

**Comment by cbalint13** [comment]
> I propose to add a bit of licensing info around the test? see [patch.txt](https://github.com/sylefeb/Silice/files/8609473/patch.txt)

* Added the license header, can review again.

I think we still have the best practice here, given this [thread](https://gitlab.kitware.com/cmake/cmake/-/issues/17834) on upstream **cmake** package.
Best would be some internal cmake helper to find for us the flag ("one-liner"), but it seems we have to wait for such.
 
> (I did not find how to push on the PR :) ; if you prefer I can merge the PR and then apply the change?)

* Only project author can push the PR, but you can merge *your other way* I really don't mind :)

Thank you Sylvain !

**Comment by sylefeb** [comment]
Looking perfect, thanks!

**Pull request merged**
