### PR TITLE
Preliminary macOS support

### PR DESCRIPTION
**Pull request by osnr**
I tested:
- `icarus_bare.sh ../../divint_bare/main.ice`
- `icestick_bare.sh ../../ice-v/ice-v.ice`
- `ulx3s_bare.sh blinky.ice`
- `verilator_sdram_vga.sh ../../vga_text_buffer/vga_text_buffer.ice`

and all worked fine (with a real icestick and ULX3S). I don't think this should break anything on other platforms, but please test if you can :-) 

It's a pretty straightforward port. clang seems to be a little stricter than the compilers you're using on Windows and Linux, so most of the changes are to get things to pass it.

Attached are additional changes that are needed but didn't seem right to put in the code (basically, 1. getting rid of hard-coded environment variables with `mingw32` 2. changing the compiler prefix from `riscv64-linux` to `riscv64-unknown` which is how it's installed on my Mac).
[other_mac_changes.txt](https://github.com/sylefeb/Silice/files/5360431/other_mac_changes.txt)

### CODE REVIEW

**Comment by sylefeb** [comment]
Thanks for looking into this! I'll go through it shortly ; need to check against the 'wip' branch were most development occurs.

**Comment by sylefeb** [comment]
Thanks again  - I just merged in wip branch, however I suspect an issue. The CMake was setting c++ 14 as standard but the latest Silice requires c++ 17. Will that prevent ANTLR to compile? Maybe we'll have to update it?

**Comment by sylefeb** [comment]
I just pushed on wip some changes to allow compilation on clang (tested on Ubuntu clang 6.0, working here). @osnr would you be able to test on macos? Thank you!

**Comment by osnr** [comment]
Great! I'll clone wip and test it sometime in the next few days when I have time.

**Comment by osnr** [comment]
These work great immediately:

- `Silice/projects/divint_bare $ make icarus`
- `Silice/projects/blinky $ make ulx3s`

This works with [patching](https://github.com/sylefeb/Silice/compare/master...osnr:osnr-mac?expand=1) to `compile_c.sh` to support `riscv64-unknown` toolchain:

- `Silice/projects/ice-v $ make icestick`

This works, but needs the manual override to point to Verilator build dir:

- `Silice/projects/vga_text_buffer $ VERILATOR_ROOT=/Users/osnr/aux/verilator make verilator`

**Comment by sylefeb** [comment]
Thanks for testing! I'll see how to adjust the script.

**Pull request merged**
